FROM node:14.15-alpine

#WORKDIR /app
#
#COPY --from=download /front/jd-homeworks/diploma/ /app
##
#RUN npm install
#COPY ../jd-homeworks/diploma/netology-diplom-frontend /front

#WORKDIR /front

RUN apk add git

RUN git clone https://github.com/netology-code/jd-homeworks.git

WORKDIR /jd-homeworks/diploma/netology-diplom-frontend

RUN npm install

#RUN npm build

RUN echo VUE_APP_BASE_URL=http://localhost:8081 > .env

#VOLUME /tsttmp /jd-homeworks/diploma/netology-diplom-frontend

#ENTRYPOINT ["npm run serve"]
#
CMD [ "npm", "run", "serve" ]

#CMD [ "npm", "run", "build" ]